import { Ingredient } from "@/types";

export const INGREDIENTS: Ingredient[] = [
  {
    name: "broccoli",
    calories: 35,
    protein: 2.4,
    fat: 0.4,
    carbs: 7.2,
    fiber: 2.6,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "lentils",
    calories: 116,
    protein: 9,
    fat: 0.4,
    carbs: 20,
    fiber: 7.9,
    glycemicIndex: 32,
    category: "protein",
    vegetarian: true
  },
  {
    name: "chickpeas",
    calories: 164,
    protein: 8.9,
    fat: 2.6,
    carbs: 27.4,
    fiber: 7.6,
    glycemicIndex: 28,
    category: "protein",
    vegetarian: true
  },
  {
    name: "white beans",
    calories: 139,
    protein: 9.7,
    fat: 0.4,
    carbs: 25,
    fiber: 6.3,
    glycemicIndex: 31,
    category: "protein",
    vegetarian: true
  },
  {
    name: "red beans",
    calories: 127,
    protein: 8.7,
    fat: 0.5,
    carbs: 22.8,
    fiber: 6.4,
    glycemicIndex: 29,
    category: "protein",
    vegetarian: true
  },
  {
    name: "black beans",
    calories: 132,
    protein: 8.9,
    fat: 0.5,
    carbs: 23.7,
    fiber: 8.7,
    glycemicIndex: 30,
    category: "protein",
    vegetarian: true
  },
  {
    name: "tofu",
    calories: 76,
    protein: 8,
    fat: 4.8,
    carbs: 1.9,
    fiber: 0.3,
    glycemicIndex: 15,
    category: "protein",
    vegetarian: true,
    allergens: ["soy"]
  },
  {
    name: "chicken breast",
    calories: 165,
    protein: 31,
    fat: 3.6,
    carbs: 0,
    fiber: 0,
    glycemicIndex: 0,
    category: "protein",
    vegetarian: false
  },
  {
    name: "turkey breast",
    calories: 157,
    protein: 29,
    fat: 3.2,
    carbs: 0,
    fiber: 0,
    glycemicIndex: 0,
    category: "protein",
    vegetarian: false
  },
  {
    name: "mushrooms",
    calories: 22,
    protein: 3.1,
    fat: 0.3,
    carbs: 3.3,
    fiber: 1,
    glycemicIndex: 10,
    portionGrams: 150,
    category: "protein",
    vegetarian: true
  },
  {
    name: "dill",
    calories: 43,
    protein: 3.5,
    fat: 1.1,
    carbs: 7,
    fiber: 2.1,
    glycemicIndex: 5,
    portionGrams: 5,
    category: "spices",
    vegetarian: true
  },
  {
    name: "salmon",
    calories: 208,
    protein: 20,
    fat: 13,
    carbs: 0,
    fiber: 0,
    glycemicIndex: 0,
    category: "protein",
    vegetarian: false,
    allergens: ["fish"]
  },
  {
    name: "cod",
    calories: 82,
    protein: 18,
    fat: 0.7,
    carbs: 0,
    fiber: 0,
    glycemicIndex: 0,
    category: "protein",
    vegetarian: false,
    allergens: ["fish"]
  },
  {
    name: "quinoa",
    calories: 120,
    protein: 4.4,
    fat: 1.9,
    carbs: 21.3,
    fiber: 2.8,
    glycemicIndex: 53,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "buckwheat",
    calories: 92,
    protein: 3.4,
    fat: 0.6,
    carbs: 19.9,
    fiber: 2.7,
    glycemicIndex: 49,
    portionGrams: 100,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "potato",
    calories: 87,
    protein: 1.9,
    fat: 0.1,
    carbs: 20.1,
    fiber: 1.8,
    glycemicIndex: 78,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "sweet potato",
    calories: 86,
    protein: 1.6,
    fat: 0.1,
    carbs: 20.1,
    fiber: 3,
    glycemicIndex: 61,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "eggs",
    calories: 155,
    protein: 13,
    fat: 11,
    carbs: 1.1,
    fiber: 0,
    glycemicIndex: 0,
    portionGrams: 90,
    category: "protein",
    vegetarian: true,
    allergens: ["egg"]
  },
  {
    name: "egg whites",
    calories: 52,
    protein: 11,
    fat: 0.2,
    carbs: 0.7,
    fiber: 0,
    glycemicIndex: 0,
    category: "protein",
    vegetarian: true,
    allergens: ["egg"]
  },
  {
    name: "spinach",
    calories: 23,
    protein: 2.9,
    fat: 0.4,
    carbs: 3.6,
    fiber: 2.2,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "olive oil",
    calories: 119,
    protein: 0,
    fat: 13.5,
    carbs: 0,
    fiber: 0,
    glycemicIndex: 0,
    category: "fats",
    vegetarian: true
  },
  {
    name: "tahini",
    calories: 89,
    protein: 2.6,
    fat: 8.1,
    carbs: 3.2,
    fiber: 1.4,
    glycemicIndex: 35,
    category: "fats",
    vegetarian: true,
    allergens: ["sesame"]
  },
  {
    name: "almond butter",
    calories: 98,
    protein: 3.4,
    fat: 9,
    carbs: 3.4,
    fiber: 1.8,
    glycemicIndex: 15,
    category: "fats",
    vegetarian: true,
    allergens: ["tree nuts"]
  },
  {
    name: "light coconut milk",
    calories: 45,
    protein: 0.5,
    fat: 4.5,
    carbs: 1.7,
    fiber: 0.2,
    glycemicIndex: 35,
    category: "liquid",
    vegetarian: true
  },
  {
    name: "cream",
    calories: 340,
    protein: 2.8,
    fat: 36,
    carbs: 2.6,
    fiber: 0,
    glycemicIndex: 15,
    portionGrams: 50,
    category: "liquid",
    vegetarian: true,
    allergens: ["dairy"]
  },
  {
    name: "plant-based cream",
    calories: 110,
    protein: 1.5,
    fat: 7,
    carbs: 9,
    fiber: 0,
    glycemicIndex: 40,
    portionGrams: 50,
    category: "liquid",
    vegetarian: true
  },
  {
    name: "unsweetened almond milk",
    calories: 17,
    protein: 0.6,
    fat: 1.5,
    carbs: 0.6,
    fiber: 0.2,
    glycemicIndex: 25,
    category: "liquid",
    vegetarian: true,
    allergens: ["tree nuts"]
  },
  {
    name: "greek yogurt",
    calories: 59,
    protein: 10,
    fat: 0.4,
    carbs: 3.6,
    fiber: 0,
    glycemicIndex: 11,
    category: "liquid",
    vegetarian: true,
    allergens: ["dairy"]
  },
  {
    name: "lemon juice",
    calories: 3,
    protein: 0.1,
    fat: 0,
    carbs: 1,
    fiber: 0.1,
    glycemicIndex: 20,
    portionGrams: 15,
    category: "liquid",
    vegetarian: true
  },
  {
    name: "vegetable broth",
    calories: 15,
    protein: 0.6,
    fat: 0.3,
    carbs: 2.5,
    fiber: 0.2,
    glycemicIndex: 5,
    category: "liquid",
    vegetarian: true
  },
  {
    name: "turmeric",
    calories: 9,
    protein: 0.3,
    fat: 0.1,
    carbs: 1.7,
    fiber: 0.7,
    glycemicIndex: 10,
    category: "spices",
    vegetarian: true
  },
  {
    name: "cinnamon",
    calories: 6,
    protein: 0.1,
    fat: 0,
    carbs: 2.1,
    fiber: 1.4,
    glycemicIndex: 5,
    category: "spices",
    vegetarian: true
  },
  {
    name: "cumin",
    calories: 8,
    protein: 0.4,
    fat: 0.4,
    carbs: 0.9,
    fiber: 0.4,
    glycemicIndex: 0,
    category: "spices",
    vegetarian: true
  },
  {
    name: "coriander",
    calories: 25,
    protein: 2.1,
    fat: 0.9,
    carbs: 4.3,
    fiber: 2.8,
    glycemicIndex: 0,
    category: "spices",
    vegetarian: true
  },
  {
    name: "curry powder",
    calories: 22,
    protein: 1.6,
    fat: 0.9,
    carbs: 4.1,
    fiber: 2.6,
    glycemicIndex: 0,
    category: "spices",
    vegetarian: true
  },
  {
    name: "garam masala",
    calories: 25,
    protein: 1.3,
    fat: 1,
    carbs: 4.5,
    fiber: 2.4,
    glycemicIndex: 0,
    category: "spices",
    vegetarian: true
  },
  {
    name: "asafoetida",
    calories: 297,
    protein: 4,
    fat: 1.1,
    carbs: 67.8,
    fiber: 4.1,
    glycemicIndex: 0,
    portionGrams: 1,
    category: "spices",
    vegetarian: true
  },
  {
    name: "cilantro",
    calories: 23,
    protein: 2.1,
    fat: 0.5,
    carbs: 3.7,
    fiber: 2.8,
    glycemicIndex: 5,
    portionGrams: 5,
    category: "spices",
    vegetarian: true
  },
  {
    name: "paprika",
    calories: 6,
    protein: 0.3,
    fat: 0.3,
    carbs: 1.2,
    fiber: 0.8,
    glycemicIndex: 0,
    category: "spices",
    vegetarian: true
  },
  {
    name: "black pepper",
    calories: 3,
    protein: 0.1,
    fat: 0,
    carbs: 0.6,
    fiber: 0.3,
    glycemicIndex: 0,
    category: "spices",
    vegetarian: true
  },
  {
    name: "garlic",
    calories: 4,
    protein: 0.2,
    fat: 0,
    carbs: 1,
    fiber: 0.2,
    glycemicIndex: 10,
    category: "spices",
    vegetarian: true
  },
  {
    name: "ginger",
    calories: 8,
    protein: 0.2,
    fat: 0.1,
    carbs: 1.8,
    fiber: 0.2,
    glycemicIndex: 15,
    category: "spices",
    vegetarian: true
  },
  {
    name: "oregano",
    calories: 3,
    protein: 0.1,
    fat: 0,
    carbs: 0.7,
    fiber: 0.4,
    glycemicIndex: 0,
    category: "spices",
    vegetarian: true
  },
  {
    name: "thyme",
    calories: 3,
    protein: 0.1,
    fat: 0.1,
    carbs: 0.7,
    fiber: 0.5,
    glycemicIndex: 0,
    category: "spices",
    vegetarian: true
  },
  {
    name: "basil",
    calories: 2,
    protein: 0.2,
    fat: 0,
    carbs: 0.3,
    fiber: 0.2,
    glycemicIndex: 0,
    category: "spices",
    vegetarian: true
  },
  {
    name: "bay leaf",
    calories: 3,
    protein: 0.1,
    fat: 0.1,
    carbs: 0.7,
    fiber: 0.5,
    glycemicIndex: 0,
    portionGrams: 1,
    category: "spices",
    vegetarian: true
  },
  {
    name: "smoked paprika",
    calories: 6,
    protein: 0.3,
    fat: 0.3,
    carbs: 1.1,
    fiber: 0.7,
    glycemicIndex: 0,
    category: "spices",
    vegetarian: true
  },
  {
    name: "parsley",
    calories: 36,
    protein: 3,
    fat: 0.8,
    carbs: 6.3,
    fiber: 3.3,
    glycemicIndex: 5,
    portionGrams: 5,
    category: "spices",
    vegetarian: true
  },
  {
    name: "shallot",
    calories: 72,
    protein: 2.5,
    fat: 0.1,
    carbs: 16.8,
    fiber: 3.2,
    glycemicIndex: 15,
    portionGrams: 30,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "vanilla",
    calories: 2,
    protein: 0,
    fat: 0,
    carbs: 0.1,
    fiber: 0,
    glycemicIndex: 0,
    category: "spices",
    vegetarian: true
  },
  {
    name: "chia seeds",
    calories: 486,
    protein: 16.5,
    fat: 30.7,
    carbs: 42.1,
    fiber: 34.4,
    glycemicIndex: 1,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "banana",
    calories: 89,
    protein: 1.1,
    fat: 0.3,
    carbs: 23,
    fiber: 2.6,
    glycemicIndex: 51,
    portionGrams: 60,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "protein powder",
    calories: 400,
    protein: 80,
    fat: 5,
    carbs: 10,
    fiber: 0,
    glycemicIndex: 35,
    portionGrams: 20,
    category: "protein",
    vegetarian: true
  },
  {
    name: "zucchini",
    calories: 17,
    protein: 1.2,
    fat: 0.3,
    carbs: 3.1,
    fiber: 1,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "eggplant",
    calories: 25,
    protein: 1,
    fat: 0.2,
    carbs: 6,
    fiber: 3,
    glycemicIndex: 15,
    portionGrams: 200,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "feta cheese",
    calories: 264,
    protein: 14.2,
    fat: 21.3,
    carbs: 4.1,
    fiber: 0,
    glycemicIndex: 0,
    portionGrams: 50,
    category: "protein",
    vegetarian: true,
    allergens: ["dairy"]
  },
  {
    name: "honey",
    calories: 304,
    protein: 0.3,
    fat: 0,
    carbs: 82.4,
    fiber: 0,
    glycemicIndex: 55,
    portionGrams: 7,
    category: "spices",
    vegetarian: true
  },
  {
    name: "mint",
    calories: 70,
    protein: 3.8,
    fat: 0.9,
    carbs: 14.9,
    fiber: 8,
    glycemicIndex: 5,
    portionGrams: 5,
    category: "spices",
    vegetarian: true
  },
  {
    name: "pomegranate seeds",
    calories: 83,
    protein: 1.7,
    fat: 1.2,
    carbs: 18.7,
    fiber: 4,
    glycemicIndex: 35,
    portionGrams: 20,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "pumpkin",
    calories: 26,
    protein: 1,
    fat: 0.1,
    carbs: 6.5,
    fiber: 0.5,
    glycemicIndex: 64,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "bell pepper",
    calories: 31,
    protein: 1,
    fat: 0.3,
    carbs: 6,
    fiber: 2.1,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "cauliflower",
    calories: 25,
    protein: 1.9,
    fat: 0.3,
    carbs: 5,
    fiber: 2,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "green beans",
    calories: 31,
    protein: 1.8,
    fat: 0.2,
    carbs: 7,
    fiber: 3.4,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "green peas",
    calories: 84,
    protein: 5.4,
    fat: 0.4,
    carbs: 15,
    fiber: 5.7,
    glycemicIndex: 51,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "asparagus",
    calories: 20,
    protein: 2.2,
    fat: 0.1,
    carbs: 3.9,
    fiber: 2.1,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "cucumber",
    calories: 15,
    protein: 0.7,
    fat: 0.1,
    carbs: 3.6,
    fiber: 0.5,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "tomato",
    calories: 18,
    protein: 0.9,
    fat: 0.2,
    carbs: 3.9,
    fiber: 1.2,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "tomato paste",
    calories: 82,
    protein: 4.3,
    fat: 0.5,
    carbs: 18.9,
    fiber: 4.1,
    glycemicIndex: 35,
    portionGrams: 15,
    category: "liquid",
    vegetarian: true
  },
  {
    name: "berries",
    calories: 57,
    protein: 0.7,
    fat: 0.3,
    carbs: 14.5,
    fiber: 4.2,
    glycemicIndex: 25,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "oats",
    calories: 389,
    protein: 16.9,
    fat: 6.9,
    carbs: 66.3,
    fiber: 10.6,
    glycemicIndex: 55,
    portionGrams: 50,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "water",
    calories: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    fiber: 0,
    glycemicIndex: 0,
    portionGrams: 200,
    category: "liquid",
    vegetarian: true
  },
  {
    name: "milk",
    calories: 52,
    protein: 3.4,
    fat: 2,
    carbs: 4.8,
    fiber: 0,
    glycemicIndex: 27,
    portionGrams: 100,
    category: "liquid",
    vegetarian: true,
    allergens: ["dairy"]
  },
  {
    name: "flax seeds",
    calories: 534,
    protein: 18.3,
    fat: 42.2,
    carbs: 28.9,
    fiber: 27.3,
    glycemicIndex: 35,
    portionGrams: 10,
    category: "fats",
    vegetarian: true
  },
  {
    name: "butter",
    calories: 717,
    protein: 0.9,
    fat: 81.1,
    carbs: 0.1,
    fiber: 0,
    glycemicIndex: 14,
    portionGrams: 5,
    category: "fats",
    vegetarian: true,
    allergens: ["dairy"]
  },
  {
    name: "soft cheese",
    calories: 105,
    protein: 12,
    fat: 5,
    carbs: 2,
    fiber: 0,
    glycemicIndex: 30,
    portionGrams: 30,
    category: "protein",
    vegetarian: true,
    allergens: ["dairy"]
  },
  {
    name: "fresh herbs",
    calories: 40,
    protein: 3,
    fat: 0.6,
    carbs: 6,
    fiber: 3,
    glycemicIndex: 10,
    portionGrams: 10,
    category: "spices",
    vegetarian: true
  },
  {
    name: "sourdough bread",
    calories: 250,
    protein: 8.9,
    fat: 2.1,
    carbs: 49,
    fiber: 2.7,
    glycemicIndex: 54,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "whole grain bread",
    calories: 247,
    protein: 8.8,
    fat: 3.4,
    carbs: 43.1,
    fiber: 6.8,
    glycemicIndex: 49,
    portionGrams: 40,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "crackers",
    calories: 400,
    protein: 10,
    fat: 10,
    carbs: 68,
    fiber: 10,
    glycemicIndex: 65,
    portionGrams: 20,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "brown rice",
    calories: 112,
    protein: 2.6,
    fat: 0.9,
    carbs: 23,
    fiber: 1.8,
    glycemicIndex: 68,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "carrot",
    calories: 41,
    protein: 0.9,
    fat: 0.2,
    carbs: 9.6,
    fiber: 2.8,
    glycemicIndex: 35,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "celery",
    calories: 16,
    protein: 0.7,
    fat: 0.2,
    carbs: 3,
    fiber: 1.6,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "onion",
    calories: 40,
    protein: 1.1,
    fat: 0.1,
    carbs: 9.3,
    fiber: 1.7,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "cabbage",
    calories: 25,
    protein: 1.3,
    fat: 0.1,
    carbs: 5.8,
    fiber: 2.5,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "beets",
    calories: 43,
    protein: 1.6,
    fat: 0.2,
    carbs: 9.6,
    fiber: 2.8,
    glycemicIndex: 64,
    portionGrams: 150,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "beef",
    calories: 198,
    protein: 26,
    fat: 10,
    carbs: 0,
    fiber: 0,
    glycemicIndex: 0,
    category: "protein",
    vegetarian: false
  },
  {
    name: "sour cream",
    calories: 193,
    protein: 3.2,
    fat: 19,
    carbs: 3.2,
    fiber: 0,
    glycemicIndex: 15,
    portionGrams: 30,
    category: "fats",
    vegetarian: true,
    allergens: ["dairy"]
  },
  {
    name: "vinegar",
    calories: 22,
    protein: 0,
    fat: 0,
    carbs: 0.9,
    fiber: 0,
    glycemicIndex: 0,
    portionGrams: 10,
    category: "spices",
    vegetarian: true
  },
  {
    name: "cottage cheese",
    calories: 98,
    protein: 11.1,
    fat: 4.3,
    carbs: 3.4,
    fiber: 0,
    glycemicIndex: 30,
    category: "protein",
    vegetarian: true,
    allergens: ["dairy"]
  },
  {
    name: "apple",
    calories: 52,
    protein: 0.3,
    fat: 0.2,
    carbs: 13.8,
    fiber: 2.4,
    glycemicIndex: 36,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "corn",
    calories: 86,
    protein: 3.3,
    fat: 1.2,
    carbs: 18.7,
    fiber: 2,
    glycemicIndex: 52,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "hummus",
    calories: 166,
    protein: 7.9,
    fat: 9.6,
    carbs: 14,
    fiber: 6,
    glycemicIndex: 38,
    category: "protein",
    vegetarian: true,
    allergens: ["sesame"]
  },
  {
    name: "tuna",
    calories: 116,
    protein: 25.5,
    fat: 0.8,
    carbs: 0,
    fiber: 0,
    glycemicIndex: 0,
    category: "protein",
    vegetarian: false,
    allergens: ["fish"]
  },
  {
    name: "lettuce",
    calories: 15,
    protein: 1.4,
    fat: 0.2,
    carbs: 2.9,
    fiber: 1.3,
    glycemicIndex: 10,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "radish",
    calories: 16,
    protein: 0.7,
    fat: 0.1,
    carbs: 3.4,
    fiber: 1.6,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "olives",
    calories: 115,
    protein: 0.8,
    fat: 10.9,
    carbs: 6.3,
    fiber: 3.2,
    glycemicIndex: 15,
    portionGrams: 20,
    category: "fats",
    vegetarian: true
  },
  {
    name: "croutons",
    calories: 395,
    protein: 11.1,
    fat: 14.9,
    carbs: 55,
    fiber: 2.4,
    glycemicIndex: 70,
    portionGrams: 15,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "mustard",
    calories: 66,
    protein: 4,
    fat: 3.3,
    carbs: 5.8,
    fiber: 3.3,
    glycemicIndex: 15,
    portionGrams: 5,
    category: "spices",
    vegetarian: true
  },
  {
    name: "soy sauce",
    calories: 53,
    protein: 5.6,
    fat: 0,
    carbs: 4.9,
    fiber: 0.8,
    glycemicIndex: 15,
    portionGrams: 15,
    category: "liquid",
    vegetarian: true
  },
  {
    name: "dark chocolate",
    calories: 598,
    protein: 7.8,
    fat: 52.4,
    carbs: 28.4,
    fiber: 11,
    glycemicIndex: 23,
    category: "fats",
    vegetarian: true
  },
  {
    name: "tempeh",
    calories: 193,
    protein: 19,
    fat: 11.4,
    carbs: 9.4,
    fiber: 8,
    glycemicIndex: 15,
    category: "protein",
    vegetarian: true,
    allergens: ["soy"]
  },
  {
    name: "almonds",
    calories: 579,
    protein: 21.2,
    fat: 49.9,
    carbs: 21.6,
    fiber: 12.5,
    glycemicIndex: 15,
    portionGrams: 15,
    category: "protein",
    vegetarian: true,
    allergens: ["tree nuts"]
  },
  {
    name: "coconut flakes",
    calories: 660,
    protein: 6.9,
    fat: 64,
    carbs: 23.7,
    fiber: 16.3,
    glycemicIndex: 45,
    portionGrams: 10,
    category: "fats",
    vegetarian: true
  },
  {
    name: "sugar-free jam",
    calories: 40,
    protein: 0.3,
    fat: 0,
    carbs: 10,
    fiber: 0.5,
    glycemicIndex: 15,
    portionGrams: 15,
    category: "spices",
    vegetarian: true
  },
  {
    name: "pear",
    calories: 57,
    protein: 0.4,
    fat: 0.1,
    carbs: 15.5,
    fiber: 3.1,
    glycemicIndex: 38,
    portionGrams: 100,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "raisins",
    calories: 299,
    protein: 3.1,
    fat: 0.5,
    carbs: 79,
    fiber: 3.7,
    glycemicIndex: 64,
    portionGrams: 10,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "almond flakes",
    calories: 579,
    protein: 21.2,
    fat: 49.9,
    carbs: 21.6,
    fiber: 12.5,
    glycemicIndex: 15,
    portionGrams: 10,
    category: "fats",
    vegetarian: true,
    allergens: ["tree nuts"]
  },
  {
    name: "sweetener",
    calories: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    fiber: 0,
    glycemicIndex: 0,
    portionGrams: 2,
    category: "spices",
    vegetarian: true
  },
  {
    name: "cheddar",
    calories: 403,
    protein: 25,
    fat: 33,
    carbs: 1.3,
    fiber: 0,
    glycemicIndex: 0,
    portionGrams: 50,
    category: "protein",
    vegetarian: true,
    allergens: ["dairy"]
  },
  {
    name: "chicken broth",
    calories: 7,
    protein: 1.3,
    fat: 0.1,
    carbs: 0.1,
    fiber: 0,
    glycemicIndex: 0,
    portionGrams: 200,
    category: "liquid",
    vegetarian: false
  },
  {
    name: "vegetable broth",
    calories: 5,
    protein: 0.2,
    fat: 0,
    carbs: 1,
    fiber: 0,
    glycemicIndex: 0,
    portionGrams: 200,
    category: "liquid",
    vegetarian: true
  },
  {
    name: "nutmeg",
    calories: 525,
    protein: 5.8,
    fat: 36,
    carbs: 49,
    fiber: 20,
    glycemicIndex: 15,
    portionGrams: 2,
    category: "spices",
    vegetarian: true
  },
  {
    name: "dijon mustard",
    calories: 66,
    protein: 4,
    fat: 3.3,
    carbs: 5.8,
    fiber: 3.3,
    glycemicIndex: 35,
    portionGrams: 5,
    category: "spices",
    vegetarian: true
  },
  {
    name: "pumpkin seeds",
    calories: 559,
    protein: 30,
    fat: 49,
    carbs: 10,
    fiber: 6,
    glycemicIndex: 25,
    portionGrams: 10,
    category: "fats",
    vegetarian: true
  },
  {
    name: "sunflower seeds",
    calories: 584,
    protein: 21,
    fat: 51,
    carbs: 20,
    fiber: 8.6,
    glycemicIndex: 35,
    portionGrams: 10,
    category: "fats",
    vegetarian: true
  },
  {
    name: "parmesan",
    calories: 431,
    protein: 38,
    fat: 29,
    carbs: 4.1,
    fiber: 0,
    glycemicIndex: 0,
    portionGrams: 10,
    category: "protein",
    vegetarian: true,
    allergens: ["dairy"]
  },
  {
    name: "salt",
    calories: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    fiber: 0,
    glycemicIndex: 0,
    portionGrams: 2,
    category: "spices",
    vegetarian: true
  },
  {
    name: "avocado",
    calories: 160,
    protein: 2,
    fat: 15,
    carbs: 8.5,
    fiber: 6.7,
    glycemicIndex: 10,
    portionGrams: 100,
    category: "fats",
    vegetarian: true
  },
  {
    name: "ghee",
    calories: 900,
    protein: 0,
    fat: 99.5,
    carbs: 0,
    fiber: 0,
    glycemicIndex: 0,
    portionGrams: 15,
    category: "fats",
    vegetarian: true,
    allergens: ["dairy"]
  },
  {
    name: "cayenne pepper",
    calories: 318,
    protein: 12,
    fat: 17,
    carbs: 57,
    fiber: 27,
    glycemicIndex: 15,
    portionGrams: 2,
    category: "spices",
    vegetarian: true
  },
  {
    name: "ribeye steak",
    calories: 291,
    protein: 24,
    fat: 21,
    carbs: 0,
    fiber: 0,
    glycemicIndex: 0,
    portionGrams: 200,
    category: "protein",
    vegetarian: false
  },
  {
    name: "rosemary",
    calories: 131,
    protein: 3.3,
    fat: 5.9,
    carbs: 20,
    fiber: 14,
    glycemicIndex: 5,
    portionGrams: 3,
    category: "spices",
    vegetarian: true
  },
  {
    name: "lemon zest",
    calories: 47,
    protein: 1.5,
    fat: 0.3,
    carbs: 16,
    fiber: 10,
    glycemicIndex: 20,
    portionGrams: 3,
    category: "spices",
    vegetarian: true
  },
];
