import { Ingredient } from "@/types";

export const INGREDIENTS: Ingredient[] = [
  {
    name: "broccoli",
    calories: 35,
    protein: 2.4,
    fat: 0.4,
    carbs: 7.2,
    fiber: 2.6,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "lentils",
    calories: 116,
    protein: 9,
    fat: 0.4,
    carbs: 20,
    fiber: 7.9,
    glycemicIndex: 32,
    category: "protein",
    vegetarian: true
  },
  {
    name: "chickpeas",
    calories: 164,
    protein: 8.9,
    fat: 2.6,
    carbs: 27.4,
    fiber: 7.6,
    glycemicIndex: 28,
    category: "protein",
    vegetarian: true
  },
  {
    name: "white beans",
    calories: 139,
    protein: 9.7,
    fat: 0.4,
    carbs: 25,
    fiber: 6.3,
    glycemicIndex: 31,
    category: "protein",
    vegetarian: true
  },
  {
    name: "tofu",
    calories: 76,
    protein: 8,
    fat: 4.8,
    carbs: 1.9,
    fiber: 0.3,
    glycemicIndex: 15,
    category: "protein",
    vegetarian: true,
    allergens: ["soy"]
  },
  {
    name: "chicken breast",
    calories: 165,
    protein: 31,
    fat: 3.6,
    carbs: 0,
    fiber: 0,
    glycemicIndex: 0,
    category: "protein",
    vegetarian: false
  },
  {
    name: "salmon",
    calories: 208,
    protein: 20,
    fat: 13,
    carbs: 0,
    fiber: 0,
    glycemicIndex: 0,
    category: "protein",
    vegetarian: false,
    allergens: ["fish"]
  },
  {
    name: "cod",
    calories: 82,
    protein: 18,
    fat: 0.7,
    carbs: 0,
    fiber: 0,
    glycemicIndex: 0,
    category: "protein",
    vegetarian: false,
    allergens: ["fish"]
  },
  {
    name: "quinoa",
    calories: 120,
    protein: 4.4,
    fat: 1.9,
    carbs: 21.3,
    fiber: 2.8,
    glycemicIndex: 53,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "buckwheat",
    calories: 92,
    protein: 3.4,
    fat: 0.6,
    carbs: 19.9,
    fiber: 2.7,
    glycemicIndex: 49,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "potato",
    calories: 87,
    protein: 1.9,
    fat: 0.1,
    carbs: 20.1,
    fiber: 1.8,
    glycemicIndex: 78,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "sweet potato",
    calories: 86,
    protein: 1.6,
    fat: 0.1,
    carbs: 20.1,
    fiber: 3,
    glycemicIndex: 61,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "eggs",
    calories: 155,
    protein: 13,
    fat: 11,
    carbs: 1.1,
    fiber: 0,
    glycemicIndex: 0,
    category: "protein",
    vegetarian: true,
    allergens: ["egg"]
  },
  {
    name: "egg whites",
    calories: 52,
    protein: 11,
    fat: 0.2,
    carbs: 0.7,
    fiber: 0,
    glycemicIndex: 0,
    category: "protein",
    vegetarian: true,
    allergens: ["egg"]
  },
  {
    name: "spinach",
    calories: 23,
    protein: 2.9,
    fat: 0.4,
    carbs: 3.6,
    fiber: 2.2,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "olive oil",
    calories: 119,
    protein: 0,
    fat: 13.5,
    carbs: 0,
    fiber: 0,
    glycemicIndex: 0,
    category: "fats",
    vegetarian: true
  },
  {
    name: "tahini",
    calories: 89,
    protein: 2.6,
    fat: 8.1,
    carbs: 3.2,
    fiber: 1.4,
    glycemicIndex: 35,
    category: "fats",
    vegetarian: true,
    allergens: ["sesame"]
  },
  {
    name: "almond butter",
    calories: 98,
    protein: 3.4,
    fat: 9,
    carbs: 3.4,
    fiber: 1.8,
    glycemicIndex: 15,
    category: "fats",
    vegetarian: true,
    allergens: ["tree nuts"]
  },
  {
    name: "light coconut milk",
    calories: 45,
    protein: 0.5,
    fat: 4.5,
    carbs: 1.7,
    fiber: 0.2,
    glycemicIndex: 35,
    category: "liquid",
    vegetarian: true
  },
  {
    name: "unsweetened almond milk",
    calories: 17,
    protein: 0.6,
    fat: 1.5,
    carbs: 0.6,
    fiber: 0.2,
    glycemicIndex: 25,
    category: "liquid",
    vegetarian: true,
    allergens: ["tree nuts"]
  },
  {
    name: "greek yogurt",
    calories: 59,
    protein: 10,
    fat: 0.4,
    carbs: 3.6,
    fiber: 0,
    glycemicIndex: 11,
    category: "liquid",
    vegetarian: true,
    allergens: ["dairy"]
  },
  {
    name: "lemon juice",
    calories: 3,
    protein: 0.1,
    fat: 0,
    carbs: 1,
    fiber: 0.1,
    glycemicIndex: 20,
    category: "liquid",
    vegetarian: true
  },
  {
    name: "vegetable broth",
    calories: 15,
    protein: 0.6,
    fat: 0.3,
    carbs: 2.5,
    fiber: 0.2,
    glycemicIndex: 5,
    category: "liquid",
    vegetarian: true
  },
  {
    name: "turmeric",
    calories: 9,
    protein: 0.3,
    fat: 0.1,
    carbs: 1.7,
    fiber: 0.7,
    glycemicIndex: 10,
    category: "spices",
    vegetarian: true
  },
  {
    name: "cinnamon",
    calories: 6,
    protein: 0.1,
    fat: 0,
    carbs: 2.1,
    fiber: 1.4,
    glycemicIndex: 5,
    category: "spices",
    vegetarian: true
  },
  {
    name: "cumin",
    calories: 8,
    protein: 0.4,
    fat: 0.4,
    carbs: 0.9,
    fiber: 0.4,
    glycemicIndex: 0,
    category: "spices",
    vegetarian: true
  },
  {
    name: "paprika",
    calories: 6,
    protein: 0.3,
    fat: 0.3,
    carbs: 1.2,
    fiber: 0.8,
    glycemicIndex: 0,
    category: "spices",
    vegetarian: true
  },
  {
    name: "black pepper",
    calories: 3,
    protein: 0.1,
    fat: 0,
    carbs: 0.6,
    fiber: 0.3,
    glycemicIndex: 0,
    category: "spices",
    vegetarian: true
  },
  {
    name: "garlic",
    calories: 4,
    protein: 0.2,
    fat: 0,
    carbs: 1,
    fiber: 0.2,
    glycemicIndex: 10,
    category: "spices",
    vegetarian: true
  },
  {
    name: "oregano",
    calories: 3,
    protein: 0.1,
    fat: 0,
    carbs: 0.7,
    fiber: 0.4,
    glycemicIndex: 0,
    category: "spices",
    vegetarian: true
  },
  {
    name: "vanilla",
    calories: 2,
    protein: 0,
    fat: 0,
    carbs: 0.1,
    fiber: 0,
    glycemicIndex: 0,
    category: "spices",
    vegetarian: true
  },
  {
    name: "chia seeds",
    calories: 486,
    protein: 16.5,
    fat: 30.7,
    carbs: 42.1,
    fiber: 34.4,
    glycemicIndex: 1,
    category: "carbs",
    vegetarian: true
  },
  {
    name: "zucchini",
    calories: 17,
    protein: 1.2,
    fat: 0.3,
    carbs: 3.1,
    fiber: 1,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "eggplant",
    calories: 25,
    protein: 1,
    fat: 0.2,
    carbs: 6,
    fiber: 3,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "pumpkin",
    calories: 26,
    protein: 1,
    fat: 0.1,
    carbs: 6.5,
    fiber: 0.5,
    glycemicIndex: 64,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "bell pepper",
    calories: 31,
    protein: 1,
    fat: 0.3,
    carbs: 6,
    fiber: 2.1,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "cauliflower",
    calories: 25,
    protein: 1.9,
    fat: 0.3,
    carbs: 5,
    fiber: 2,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "green beans",
    calories: 31,
    protein: 1.8,
    fat: 0.2,
    carbs: 7,
    fiber: 3.4,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "green peas",
    calories: 84,
    protein: 5.4,
    fat: 0.4,
    carbs: 15,
    fiber: 5.7,
    glycemicIndex: 51,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "asparagus",
    calories: 20,
    protein: 2.2,
    fat: 0.1,
    carbs: 3.9,
    fiber: 2.1,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "cucumber",
    calories: 15,
    protein: 0.7,
    fat: 0.1,
    carbs: 3.6,
    fiber: 0.5,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "tomato",
    calories: 18,
    protein: 0.9,
    fat: 0.2,
    carbs: 3.9,
    fiber: 1.2,
    glycemicIndex: 15,
    category: "vegetables",
    vegetarian: true
  },
  {
    name: "berries",
    calories: 57,
    protein: 0.7,
    fat: 0.3,
    carbs: 14.5,
    fiber: 4.2,
    glycemicIndex: 25,
    category: "vegetables",
    vegetarian: true
  }
];
