/** Keys must match `Ingredient.name` exactly (lowercase lookup in UI). */
export const INGREDIENT_SUBSTITUTIONS: Record<string, string[]> = {
  potato: ["sweet potato", "pumpkin", "zucchini"],
  "sweet potato": ["pumpkin", "zucchini", "carrot"],
  pumpkin: ["zucchini", "sweet potato", "carrot"],
  zucchini: ["eggplant", "pumpkin", "broccoli"],
  eggplant: ["zucchini", "broccoli", "cauliflower"],
  broccoli: ["cauliflower", "green beans", "zucchini"],
  cauliflower: ["broccoli", "zucchini", "green beans"],
  "green peas": ["green beans", "broccoli", "zucchini"],
  "green beans": ["green peas", "broccoli", "zucchini"],
  quinoa: ["buckwheat", "brown rice", "oats"],
  buckwheat: ["quinoa", "brown rice", "oats"],
  "brown rice": ["quinoa", "buckwheat", "oats"],
  oats: ["quinoa", "buckwheat", "brown rice"],
  "sourdough bread": ["buckwheat", "quinoa", "sweet potato"],
  corn: ["chickpeas", "lentils", "quinoa"],
  apple: ["berries", "cucumber", "carrot"],
  eggs: ["tofu", "egg whites", "tempeh"],
  "egg whites": ["tofu", "eggs"],
  "chicken breast": ["tofu", "tempeh", "chickpeas"],
  tuna: ["tofu", "chickpeas", "cottage cheese"],
  salmon: ["cod", "tofu", "tempeh"],
  cod: ["salmon", "tofu", "tempeh"],
  lentils: ["chickpeas", "white beans", "tofu"],
  chickpeas: ["lentils", "white beans", "tofu"],
  "white beans": ["chickpeas", "lentils", "tofu"],
  tofu: ["tempeh", "chickpeas", "lentils"],
  tempeh: ["tofu", "chickpeas", "lentils"],
  tomato: ["bell pepper", "zucchini", "cucumber"],
  spinach: ["zucchini", "broccoli", "green beans"],
  "bell pepper": ["zucchini", "tomato", "broccoli"],
  "greek yogurt": ["cottage cheese", "unsweetened almond milk", "tofu"],
  "cottage cheese": ["greek yogurt", "tofu"],
  "feta cheese": ["cottage cheese", "greek yogurt", "tofu"],
  "light coconut milk": ["unsweetened almond milk", "greek yogurt"],
  "unsweetened almond milk": ["light coconut milk", "greek yogurt"],
  hummus: ["greek yogurt", "tahini", "cottage cheese"],
  almonds: ["chia seeds", "berries", "tofu"],
  carrot: ["zucchini", "celery", "cucumber"],
  celery: ["cucumber", "carrot", "bell pepper"],
  cucumber: ["celery", "zucchini", "carrot"],
  onion: ["garlic", "zucchini", "celery"],
  cabbage: ["spinach", "broccoli", "cauliflower"],
  beets: ["carrot", "tomato", "bell pepper"],
  "dark chocolate": ["almonds", "berries", "chia seeds"],
  "almond butter": ["tahini", "olive oil", "hummus"]
};
